#!/bin/bash

set -e

# NVM: Install NVM (Node Version Manager)
# https://github.com/nvm-sh/nvm
if [ ! -d "$HOME/.nvm" ]
then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
fi

if [ -d "$HOME/.nvm" ]
then
    # Load NVM
    . "$NVM_DIR/nvm.sh"

    # Node: Install the latest Node LTS
    # https://nodejs.org
    nvm install --lts
fi

# VS Code: Install Extensions
extensions=(
    esbenp.prettier-vscode
    dbaeumer.vscode-eslint
    dsznajder.es7-react-js-snippets
    tamasfe.even-better-toml
    ms-azuretools.vscode-docker
    github.copilot
    mhutchie.git-graph
    xabikos.javascriptsnippets
)
for extension in "${extensions[@]}"; do
    if ! code --list-extensions | grep -q "$extension"; then
        code --install-extension "$extension"
    fi
done
