#!/bin/bash

set -e

# NVM: Install NVM (Node Version Manager)
# https://github.com/nvm-sh/nvm
if [ ! -d "$HOME/.nvm" ]
then
    curl --silent -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
fi

if [ -d "$HOME/.nvm" ]
then
    # Load NVM
    . "$NVM_DIR/nvm.sh"

    # Node: Install the latest Node LTS
    # https://nodejs.org
    nvm install --lts
fi

# Cursor: Install Extensions
extensions=(
    dbaeumer.vscode-eslint
    esbenp.prettier-vscode
    monokai.theme-monokai-pro-vscode
)
for extension in "${extensions[@]}"; do
    if ! cursor --list-extensions | grep -q "$extension"; then
        cursor --install-extension "$extension"
    fi
done
