#!/bin/bash

set -e

sudo snap install code --classic
sudo snap install slack --classic

sudo snap install discord
sudo snap connect discord:system-observe

sudo snap install libreoffice

# https://github.com/canonical/docker-snap/blob/main/README.md
sudo snap install docker

# Running Docker as normal user
# sudo addgroup --system docker
# sudo adduser $USER docker
# newgrp docker

# sudo snap disable docker
# sudo snap enable docker